#!/bin/env sh

source $DOTFILES/scripts/lang/check.sh

check 'maim' 'maim'
check 'xclip' 'xclip'
check 'pytesseract' '(<a href="https://pypi.org/project/pytesseract/">pytesseract</a>)'

maim -s /tmp/pic.png
t=$(pytesseract /tmp/pic.png)

echo $t
echo $t | xclip -sel c -r
notify-send "Text:" "$t"
