spotify-cli:
	clang ./spotify-cli.c -o ./spotify-cli -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -ldbus-1
	clang ./spotify-cli.c -g -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -ldbus-1

clean:
	rm -f spotify-cli a.out
