If:
    PathMatch: [.*\.h]
CompileFlags:
        Add: [
                -xc-header
                -std=c99,
                -g,
                -pthread,
                -Wall,
                -Wextra,
                -pedantic,
                -ferror-limit=0,
                -ftemplate-backtrace-limit=0,
            ]
-------
If:
    PathMatch: [.*\.c]
CompileFlags:
        Add: [
                -xc
                -std=c99,
                -g,
                -pthread,
                -Wall,
                -Wextra,
                -pedantic,
                -ferror-limit=0,
                -ftemplate-backtrace-limit=0,
            ]
------
If:
    PathMatch: [.*\.hpp, .*\.cpp]
CompileFlags:
            Add: [
                    -xc++,
                    -std=c++17,
                    -g,
                    -pthread,
                    -Wall,
                    -Wextra,
                    -pedantic,
                    -ferror-limit=0,
                    -ftemplate-backtrace-limit=0,
                ]
