#!/bin/bash

source ~/dotfiles/config/i3blocks/colors

device="${BLOCK_INSTANCE:-wlan0}"
status=$(cat /sys/class/net/${device}/operstate)

URGENT_VALUE=20


if [[ "${status}" == "up" ]]; then
  if [[ -d "/sys/class/net/${device}/wireless" ]]; then
    quality=$(grep ${device} /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
    echo "${quality}%"
    echo "${quality}%"
    echo $GREEN

    if [[ "${quality}" -le "${URGENT_VALUE}" ]]; then
	    echo "Down"
	    echo "down"
	    echo $RED
    fi
  else
    echo "on"
    echo "on"
    echo ""
  fi
fi
