#!/bin/env sh
SHELL=/bin/sh

main() {
	source $DOTFILES/scripts/cmlib.sh

	echo 'Init
Clean
Generate Debug
Generate Release
Generate RelWithDebInfo
Generate MinSizeRel
Clang Generate Debug
Clang Generate Release
Clang Generate RelWithDebInfo
Clang Generate MinSizeRel
GNU Generate Debug
GNU Generate Release
GNU Generate RelWithDebInfo
GNU Generate MinSizeRel
Build Debug
Build Release
Build RelWithDebInfo
Build MinSizeRel
Clang Build Debug
Clang Build Release
Clang Build RelWithDebInfo
Clang Build MinSizeRel
GNU Build Debug
GNU Build Release
GNU Build RelWithDebInfo
GNU Build MinSizeRel' |
		fzf --preview "source $DOTFILES/scripts/cmlib.sh;getPreview {}" \
			--bind "enter:execute(source $DOTFILES/scripts/cmlib.sh;runCommand {})"
}

main
