#!/bin/bash

imgLogFile=~/log/img.log
if [ ! -f $imgLogFile ]; then
	notify-send "No image log file found."
	exit 0
fi

imgDir=/home/shawn/Pictures/Wallpapers
imgIndexFile=~/.cache/imgIndex.txt
if [ ! -f $imgIndexFile ]; then
	# ls full path
	ls -1 $imgDir/* > $imgIndexFile
fi

lastImg=$(tail -n 1 $imgLogFile)

lastImgFound=false
newImg=''
while read line; do
	if [ "$line" == "$lastImg" ]; then
		lastImgFound=true
	elif $lastImgFound; then
		newImg="$line"
		break
	fi
done <<< $(cat $imgIndexFile)

echo newImg: $newImg
echo $newImg >> $imgLogFile

feh --bg-fill $newImg
