#!/bin/env bash

while true; do
	echo "================$(date)=================" >> ~/log/dwmblocks.log
	echo "================$(date)=================" >> ~/log/dwmblocks.err.log
	dwmblocks $@ 1>> ~/log/dwmblocks.log 2>> ~/log/dwmblocks.err.log
done
